services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bloiselabsdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrongPassw@rd!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    restart: unless-stopped
